name: Flat
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: execute py script
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
        run: |
          python -m venv venv
          .\venv\Scripts\python.exe -m pip install --upgrade pip
          .\venv\Scripts\python.exe -m pip install playwright==1.40.0
          .\venv\Scripts\python.exe -m pip install -r requirements.txt
          .\venv\Scripts\python.exe -m playwright install webkit
          .\venv\Scripts\python.exe postprocessing.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Latest TikTok RSS"
          git push
